apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-apline
  labels:
    app: nginx
    tag: alpine
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources: {}
        ports:
          - containerPort: 80
