# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8.3"
  config.vm.box_check_update = false

  # Network configuration
  config.vm.network "private_network", ip: "192.168.50.4"
  # Shared folders
  # By default project folder will be mounted at /vagrant
  # config.vm.synced_folder "data/", "/vagrant_data"

  # configure the parameters for VMware provider
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.memory = "4096"
    vmware.cpus = 4
    vmware.gui = false
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y nano tmux nmap-ncat
    dnf install -y git-core
    dnf install -y podman
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    cp /etc/rancher/k3s/k3s.yaml /vagrant/
    dnf copr -y enable luminoso/k9s
    dnf install -y k9s
  SHELL

end